### ISSUE TITLE
oggvorbis: add vanity import path?

### ISSUE THREAD

**Issue by mewmew** [zikichombo/ext#5]
Currently godoc.org reports that `zikichombo.org/ext/oggvorbis` is redirected to `github.com/zikichombo/ext/oggvorbis`:

> Redirected from zikichombo.org/ext/oggvorbis.
>
>  ext: github.com/zikichombo/ext/oggvorbis

This suggests that ext/oggvorbis is missing a vanity import path.

**Comment by wsc1** [comment]
ok I'll fix it.  thx

**Comment by wsc1** [comment]
done.  anything else other than tests lacking input files?
